- hosts: localhost
 
  tasks:
 
  - name: Repositories
    apt_repository: 
      repo:  ppa:webupd8team/java 
      state: present  
 
  - name: Update cache 
    apt:
      update_cache: yes
 
  - name: Dist upgrade
    apt:
      upgrade: dist
 
  - name: Install pacakges 
    apt:  
      name: "{{ item }}" 
      state: latest
    with_items:
       - oracle-java8-installer
       - xclip
       - nginx
       - php7-fpm
       - mysql-server 
       - mysql-client
       - php7.0-mysql 
       - php7.0-curl
       - php7.0-json
       - php-gettext 
       - php7.0-mbstring
       - php-xdebug
       - phpmyadmin
       - git 
       - golang
       - libxss1
       - libappindicator1
       - libindicator7
       - docker
       - gdb
 
  - name: Download latest software installer 
    get_url:
      url: {{ item[0] }}
      dest: /tmp/{{ item[1] }} 
    with_items: 
      - ['https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', 'chrome.deb']    
 
  - name: Download software installer
    unarchive:
      dest: "{ item[0] }}"
      src: "{{ item[1] }}"
      remote_src: true
    with_items:
      - ['https://download.jetbrains.com/webide/PhpStorm-2016.2.2.tar.gz', '/opt/phpstorm']
      - ['https://download.jetbrains.com/python/pycharm-community-2016.2.3.tar.gz', 'pycharm' ]

  - name: Install chrome
    apt:
      deb: /tmp/chrome.deb

  - name: install Oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  
  - name: Create workspace
    file: 
       path: /home/user/workspace 
       state: directory

  - name: Create worspace sub folder
    file: 
      path: /home/user/workspace/{{ item }}
      state: directory  
    with_items:
      - go
      - php 
      - ansible 
      - python 
      - docker
  
  - name: Configure Ngnix 
    lineinfile:
       dest: /etc/php/7.0/fpm/php.ini
       state: absent 
       regexp: "cgi\.fix_pathinfo\=1"
  - lineinfile: 
      dest: /etc/php/7.0/fpm/php.ini
      line: "cgi.fix_pathinfo=0"
 	
