- hosts: localhost
 
  tasks:
 
  - name: Repositories
    apt_repository: 
      repo:  ppa:webupd8team/java 
      state: present  
 
  - name: Update cache 
    apt:
      update_cache: yes
 
  - name: Dist upgrade
    apt:
      upgrade: dist
  
  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
 
  - name: Install pacakges 
    apt:  
      name: "{{ item }}" 
      state: latest
    with_items:
       - oracle-java8-installer
       - xclip
       - nginx
       - php7.0-fpm
       - mysql-server 
       - mysql-client
       - php7.0-mysql 
       - php7.0-curl
       - php7.0-json
       - php-gettext 
       - php7.0-mbstring
       - php-xdebug
       - phpmyadmin
       - git 
       - golang
       - libxss1
       - libappindicator1
       - libindicator7
       - docker
       - gdb
       - vim 
 
  - name: Download latest software installer 
    get_url:
      url: "{{ item.url }}"
      dest: /tmp/{{ item.file }} 
    with_items: 
      - {url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', file: 'chrome.deb'}
      - {url: 'https://downloads.slack-edge.com/linux_releases/slack-desktop-2.2.1-amd64.deb', file: 'slack.deb'}    

  - name: Create folders for IDEs
    file: 
       path: "{{ item }}"
       state: directory
    with_items:
       - /opt/phpstorm
       - /opt/pycharm 	

#  - name: Download software installer
#    unarchive:
#      dest: "{{ item.dir }}"
#      src: "{{ item.url }}"
#      remote_src: yes
#    with_items:
#      - {url: 'https://download.jetbrains.com/webide/PhpStorm-2016.2.2.tar.gz',  dir: '/opt/phpstorm'}
#      - {url: 'https://download.jetbrains.com/python/pycharm-community-2016.2.3.tar.gz', dir: '/opt/pycharm'}

  - name: Install chrome
    apt:
      deb: /tmp/{{ item }}
    with_items:
      - chrome.deb
      - slack.deb

  - name: install Oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  
  - name: Create workspace
    file: 
       path: /home/user/workspace 
       state: directory

  - name: Create worspace sub folder
    file: 
      path: /home/user/workspace/{{ item }}
      state: directory  
    with_items:
      - go
      - php 
      - ansible 
      - python 
      - docker
  
  - name: Configure Ngnix 
    replace:
       dest: /etc/php/7.0/fpm/php.ini 
       regexp: 'cgi\.fix_pathinfo=1'
       replace: 'cgi.fix_pathinfo=0'
 
